import Link from "next/link";
import { ArrowUpRight, BarChart3, CreditCard, Mic2, Music2, Play, Share2, Sparkles, Video, Users, MessageCircle } from "lucide-react";
import { Shell, PageHeader, StatCard } from "@/components/Shell";

export default function Page(){return <Shell><div className="page-wrap"><PageHeader eyebrow="Workspace overview" title="Your creative command center" description="Create, manage and share everything you make with iSing AI." action={<Link href="/create" className="primary-btn orange-btn"><Sparkles size={15}/> Create with AI</Link>}/>
<div className="dashboard-grid"><StatCard label="Songs created" value="—" detail="Live data from Supabase" icon={Music2}/><StatCard label="Videos created" value="—" detail="Live data from Supabase" icon={Video}/><StatCard label="Previews played" value="—" detail="Live data from Supabase" icon={Play}/><StatCard label="Shares" value="—" detail="Live data from Supabase" icon={Share2}/></div>
<div className="mt-5 grid gap-5 lg:grid-cols-[1.45fr_.8fr]"><section className="section-card"><div className="flex items-center justify-between"><div><h2>Start creating</h2><p className="sub">Choose a workflow and jump straight into the studio.</p></div><Link href="/create" className="text-xs font-black text-[#ff5a36]">Open studio →</Link></div><div className="card-grid mt-5">{[[Music2,"Create music","Turn an idea into a song."],[Video,"Create video","Build a visual from your music."],[Mic2,"Create a voice","Manage authorized voice profiles."],[MessageCircle,"Use WhatsApp","Create and receive music in chat."]].map(([I,t,d])=>{const Icon=I as typeof Music2;return <Link href={t.includes("video")?"/videos":t.includes("voice")?"/voices":t.includes("WhatsApp")?"/whatsapp":"/create"} key={String(t)} className="action-card"><div className="action-icon"><Icon size={17}/></div><div><b>{String(t)}</b><p>{String(d)}</p></div><div className="action-arrow"><ArrowUpRight size={16}/></div></Link>})}</div></section>
<section className="hero-panel"><div className="eyebrow !text-[#ff8c72]">iSing AI Studio</div><h2>Your next song starts with one idea.</h2><p>Describe the sound, choose the language and singer, then generate a free preview before unlocking the full creation.</p><div className="hero-actions"><Link href="/create" className="light">Open creator</Link><Link href="/whatsapp" className="dark">WhatsApp</Link></div></section></div>
<div className="mt-5 section-card"><div className="flex items-center justify-between"><div><h2>Recent activity</h2><p className="sub">Your latest creations, payments and shares will appear here.</p></div><Link href="/songs" className="text-xs font-black text-zinc-500">View library →</Link></div><div className="mt-5 empty-state"><div className="empty-icon"><Music2 size={23}/></div><h3>Your creative history is waiting</h3><p>Create your first song and it will appear here with its preview, status, payment and sharing actions.</p><Link href="/create" className="primary-btn orange-btn">Create your first song</Link></div></div>
</div></Shell>}
